require('core.globals')
require('core.options')
require('core.keymap')
require('core.autocmd')
require('core.lsp')

require('plugins.mason')
require('plugins.nvim-lspconfig')
require('plugins.nvim-treesitter')
require('plugins.colorscheme')
require('plugins.telescope')
require('plugins.nvim-tree')
require('plugins.lualine')
require('plugins.lazygit')
require('plugins.which-key')
