vim.pack.add({ "https://github.com/mason-org/mason.nvim.git" })
require("mason").setup()

vim.api.nvim_create_user_command("MasonInstallForMichal", function(opts)
    vim.cmd("MasonInstall angular-language-server")
    vim.cmd("MasonInstall docker-compose-language-service")
    vim.cmd("MasonInstall docker-language-server")
    vim.cmd("MasonInstall harper-ls")
    vim.cmd("MasonInstall json-lsp")
    vim.cmd("MasonInstall kotlin-language-server")
    vim.cmd("MasonInstall lua-language-server")
    vim.cmd("MasonInstall markdown-oxide")
    vim.cmd("MasonInstall nginx-language-server")
    vim.cmd("MasonInstall postgres-language-server")
    vim.cmd("MasonInstall pyright")
    vim.cmd("MasonInstall rust-analyzer")
    vim.cmd("MasonInstall sqlls")
    vim.cmd("MasonInstall stylua")
    vim.cmd("MasonInstall svelte-language-server")
    vim.cmd("MasonInstall xcode-build-server")
end, { desc = "Install commmon language servers", nargs = 0 })
